// <auto-generated />
using System;
using Gerencia.Repositorios.SQL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gerencia.Repositorios.SQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251025192507_MigracioInicial")]
    partial class MigracioInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gerencia.Core.Repositorios.Entidades.Disponibilidad", b =>
                {
                    b.Property<int>("DisponibilidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisponibilidadId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("DisponibilidadId");

                    b.ToTable("Disponibilidad", (string)null);

                    b.HasData(
                        new
                        {
                            DisponibilidadId = 1,
                            Nombre = "Disponible"
                        },
                        new
                        {
                            DisponibilidadId = 2,
                            Nombre = "Ocupado"
                        },
                        new
                        {
                            DisponibilidadId = 3,
                            Nombre = "Mantenimiento"
                        });
                });

            modelBuilder.Entity("Gerencia.Core.Repositorios.Entidades.EmpleadoEntidad", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PuestoId")
                        .HasColumnType("Int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EmpleadoId");

                    b.ToTable("empleado", (string)null);
                });

            modelBuilder.Entity("Gerencia.Core.Repositorios.Entidades.EmpleadoProyectoDetalleEntidad", b =>
                {
                    b.Property<int>("EmpleadoProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("Linea")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoProyectoId", "Linea");

                    b.HasIndex("ProyectoID");

                    b.ToTable("EmpleadoProyectoDetalle", (string)null);
                });

            modelBuilder.Entity("Gerencia.Core.Repositorios.Entidades.EmpleadoProyectoEntidad", b =>
                {
                    b.Property<int>("EmpleadoProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoProyectoId"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoProyectoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("EmpleadoProyecto", (string)null);
                });

            modelBuilder.Entity("Gerencia.Core.Repositorios.Entidades.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("EstadoId");

                    b.ToTable("Estado", (string)null);

                    b.HasData(
                        new
                        {
                            EstadoId = 1,
                            Nombre = "Incompleto"
                        },
                        new
                        {
                            EstadoId = 2,
                            Nombre = "En curso"
                        },
                        new
                        {
                            EstadoId = 3,
                            Nombre = "Completado"
                        });
                });

            modelBuilder.Entity("Gerencia.Core.Repositorios.Entidades.Importancia", b =>
                {
                    b.Property<int>("ImportanciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportanciaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ImportanciaId");

                    b.ToTable("Importancia", (string)null);

                    b.HasData(
                        new
                        {
                            ImportanciaId = 1,
                            Nombre = "Baja"
                        },
                        new
                        {
                            ImportanciaId = 2,
                            Nombre = "Media"
                        },
                        new
                        {
                            ImportanciaId = 3,
                            Nombre = "Alta"
                        },
                        new
                        {
                            ImportanciaId = 4,
                            Nombre = "Urgente"
                        });
                });

            modelBuilder.Entity("Gerencia.Core.Repositorios.Entidades.ProcesoEntidad", b =>
                {
                    b.Property<int>("ProcesoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcesoId"));

                    b.Property<string>("Entregables")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaTerminoEstimada")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaTerminoReal")
                        .HasColumnType("date");

                    b.Property<byte>("Finalizado")
                        .HasColumnType("tinyint");

                    b.Property<int>("ImportanciaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("Int");

                    b.HasKey("ProcesoId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ImportanciaId");

                    b.ToTable("proceso", (string)null);
                });

            modelBuilder.Entity("Gerencia.Core.Repositorios.Entidades.ProyectoEntidad", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoId"));

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyecto", (string)null);
                });

            modelBuilder.Entity("Gerencia.Core.Repositorios.Entidades.TipoPuesto", b =>
                {
                    b.Property<int>("PuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PuestoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PuestoId");

                    b.ToTable("Puesto", (string)null);

                    b.HasData(
                        new
                        {
                            PuestoId = 1,
                            Nombre = "Gerente"
                        },
                        new
                        {
                            PuestoId = 2,
                            Nombre = "Análista"
                        },
                        new
                        {
                            PuestoId = 3,
                            Nombre = "Técnico"
                        });
                });

            modelBuilder.Entity("Gerencia.Core.Repositorios.Entidades.EmpleadoProyectoDetalleEntidad", b =>
                {
                    b.HasOne("Gerencia.Core.Repositorios.Entidades.EmpleadoProyectoEntidad", "EmpleadoProyecto")
                        .WithMany("Detalles")
                        .HasForeignKey("EmpleadoProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerencia.Core.Repositorios.Entidades.ProyectoEntidad", null)
                        .WithMany()
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmpleadoProyecto");
                });

            modelBuilder.Entity("Gerencia.Core.Repositorios.Entidades.EmpleadoProyectoEntidad", b =>
                {
                    b.HasOne("Gerencia.Core.Repositorios.Entidades.EmpleadoEntidad", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gerencia.Core.Repositorios.Entidades.ProyectoEntidad", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Gerencia.Core.Repositorios.Entidades.ProcesoEntidad", b =>
                {
                    b.HasOne("Gerencia.Core.Repositorios.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gerencia.Core.Repositorios.Entidades.Importancia", "Importancia")
                        .WithMany()
                        .HasForeignKey("ImportanciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Importancia");
                });

            modelBuilder.Entity("Gerencia.Core.Repositorios.Entidades.EmpleadoProyectoEntidad", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
